// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelConnect() {
  return window['go']['main']['App']['CancelConnect']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DisableRecording(arg1) {
  return window['go']['main']['App']['DisableRecording'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function EnableRecording(arg1) {
  return window['go']['main']['App']['EnableRecording'](arg1);
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function History(arg1) {
  return window['go']['main']['App']['History'](arg1);
}

export function Publish(arg1) {
  return window['go']['main']['App']['Publish'](arg1);
}

export function QueryRecorded(arg1, arg2) {
  return window['go']['main']['App']['QueryRecorded'](arg1, arg2);
}

export function RecordedTopics() {
  return window['go']['main']['App']['RecordedTopics']();
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function Subscribe(arg1, arg2) {
  return window['go']['main']['App']['Subscribe'](arg1, arg2);
}

export function Unsubscribe(arg1) {
  return window['go']['main']['App']['Unsubscribe'](arg1);
}
