// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {mqtt} from '../models';

export function CancelConnect():Promise<void>;

export function Connect(arg1:config.Profile):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DisableRecording(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function EnableRecording(arg1:string):Promise<void>;

export function GetProfiles():Promise<Array<config.Profile>>;

export function GetSettings():Promise<config.Settings>;

export function GetVersion():Promise<string>;

export function History(arg1:string):Promise<Array<mqtt.Message>>;

export function Publish(arg1:mqtt.Message):Promise<void>;

export function QueryRecorded(arg1:string,arg2:number):Promise<Array<mqtt.Message>>;

export function RecordedTopics():Promise<Array<string>>;

export function SaveProfile(arg1:config.Profile):Promise<void>;

export function SaveSettings(arg1:config.Settings):Promise<void>;

export function Subscribe(arg1:string,arg2:number):Promise<void>;

export function Unsubscribe(arg1:string):Promise<void>;
